
var Drugs = [
    {
        name:"通宣理肺片",
        efficacy:"解表散寒，宣肺止咳",
        usedate:3,
        profac:"北京有限公司",
        unitprice:25,
        num:20,
        yea:2015,
        mouth:3,
        date:15
    },
    {
        name:"氯雷他定片",
        efficacy:"用于缓解过敏性鼻炎有关的症状",
        usedate:5,
        profac:"哈尔滨有限公司",
        unitprice:30,
        num:30,
        yea:2017,
        mouth:3,
        date:9
    },
    {
        name:"新雪片",
        efficacy:"清热解毒,用于各种热性病之发热",
        usedate:1,
        profac:"广州有限公司",
        unitprice:15,
        num:10,
        yea:2013,
        mouth:4,
        date:8
    },
    {
        name:"一清颗粒",
        efficacy:"清热泻火解毒",
        usedate:6,
        profac:"深圳有限公司",
        unitprice:20,
        num:40,
        yea:2014,
        mouth:11,
        date:20
    },
    {
        name:"甲钴胺注射液",
        efficacy:"因缺乏维生素B12引起的巨幼红细胞性贫血的治疗",
        usedate:2,
        profac:"福建金山生物制药股份有限公司",
        unitprice:10,
        num:60,
        yea:2018,
        mouth:3,
        date:9
    },
    {
        name:"人工牛黄甲硝唑胶囊",
        efficacy:"人工牛黄甲硝唑胶囊",
        usedate:2,
        profac:"吉林有限公司",
        unitprice:10,
        num:60,
        yea:2018,
        mouth:6,
        date:9
    },
    {
        name:"六味地黄丸",
        efficacy:"头晕耳鸣，腰膝酸软",
        usedate:5,
        profac:"北京同仁堂科技发展股份有限公司制药厂",
        unitprice:10,
        num:60,
        yea:2018,
        mouth:4,
        date:15
    },
    {
        name:"乳果糖口服溶液",
        efficacy:"用于治疗高血氨症及由血氨升高引起的疾病；用于治疗慢性功能性便秘",
        usedate:1,
        profac:"丹东康复制药有限公司",
        unitprice:10,
        num:60,
        yea:2015,
        mouth:6,
        date:7
    },
    {
        name:"维生素E软胶囊",
        efficacy:"用于未进食强化奶粉或有严重脂肪吸收不良母亲所生的新生儿、早产儿、低出生体重儿",
        usedate:1,
        profac:"浙江医药股份有限公司新昌制药厂",
        unitprice:10,
        num:60,
        yea:2018,
        mouth:1,
        date:9
    },
    {
        name:"迪巧儿童维D钙咀嚼片",
        efficacy:"高钙血症、高尿酸血症、含钙肾结石或有肾结石病史者禁用",
        usedate:2,
        profac:"安士制药(中山)有限公司",
        unitprice:15,
        num:30,
        yea:2013,
        mouth:3,
        date:15
    },
    {
        name:"双黄连口服液",
        efficacy:"疏风解表，清热解毒、用于外感风热所致的感冒，症见发热、咳嗽、咽痛",
        usedate:1,
        profac:"吉林有限公司",
        unitprice:10,
        num:20,
        yea:2017,
        mouth:12,
        date:9
    }
];
var information =[
    {
        name:"刘可新",
        password:230621199808245165,
        index:0
    },
    {
        name:"王文竹",
        password:230621199808245166,
        index:0

    },
    {
        name:"王习文",
        password:230621199808245167,
        index:0
    }
];
var infonum = 0;
var info = new Array();
